apiVersion: v1
kind: Service
metadata:
  name: setupjira
  labels:
    name: setupjira
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    name: setupjira