apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: postgres
  name: postgres-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
      - image: postgres
        name: postgres
        ports:
        - name: postgres
          containerPort: 5432
          hostPort: 5432
        volumeMounts:
            - name: postgres-persistent-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-persistent-storage
          gcePersistentDisk:
            pdName: mongo-disk
            fsType: ext4